use bookstoredb;

-- List all books with their authors and publishers

SELECT b.BookName, a.firstName AS AuthorFirstName, a.lastName AS AuthorLastName, p.publisherName
FROM Book b
JOIN Book_author ba ON b.book_id = ba.book_id
JOIN Author a ON ba.author_id = a.author_id
JOIN publisher p ON b.publisher_id = p.publisher_id;



-- Get books in a specific language (e.g., 'English')
SELECT b.BookName, l.languageName
FROM Book b
JOIN Book_language l ON b.language_id = l.language_id
WHERE l.languageName = 'English';


-- Find books published before 2020
-- List all customers and their contact information
-- Get customers with more than 1 address
-- List all orders with customer name, total, and date
-- Find total sales per book
-- Get order status history for a specific order
-- List shipping methods and their costs
-- Find all addresses linked to a customer


-- Analytics and Insights
-- Top 5 most ordered books
SELECT b.BookName, SUM(ol.quantity) AS TotalOrdered
FROM Book b
JOIN order_line ol ON b.book_id = ol.book_id
GROUP BY b.BookName
ORDER BY TotalOrdered DESC
LIMIT 5;




-- Total revenue generated by each publisher
SELECT p.publisherName, SUM(ol.unitPrice * ol.quantity) AS TotalRevenue
FROM Book b
JOIN order_line ol ON b.book_id = ol.book_id
JOIN publisher p ON b.publisher_id = p.publisher_id
GROUP BY p.publisherName
ORDER BY TotalRevenue DESC;